
<script src="<?php echo BASE_URL ?>web-files/js/jquery-1.11.3.min.js"></script>
<script src="<?php echo BASE_URL ?>web-files/plugins/bootstrap-3.3.6-dist/js/bootstrap.min.js"></script>
<script src="<?php echo BASE_URL ?>web-files/plugins/bootstrap-tags-input/dist/bootstrap-tagsinput.js"></script>

<script>


    $('#myTabs a').click(function (e) {
        e.preventDefault()
        $(this).tab('show')
    })


</script>