<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><?php echo SYSTEM_NAME ?></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <?php /*if (!empty($view_userData['login_ad'])) { */?>

                <ul class="nav navbar-nav">
                    <li class="active"><a href="<?php echo BASE_URL ?>">Pesquisar Produtos</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <!--<li><a><?php /*echo $view_userData['nome_completo'] */?></a></li>
                    <li><a href="<?php /*echo BASE_URL . 'site/index/logout' */?>">Sair</a></li>-->
                </ul>

            <?php /*} */?>

        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>
